import assert from "node:assert/strict";
import { access, readFile } from "node:fs/promises";
import test from "node:test";

test("build GitHub Pages autonomo e completo", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  assert.match(html, /Tavola Mia/);
  assert.match(html, /\.\/assets\//);
  await access(new URL("../dist/food/chicken-bowl.png", import.meta.url));
  await access(new URL("../dist/food/toast.png", import.meta.url));
  await access(new URL("../dist/og.png", import.meta.url));
});

test("sorgente mobile con versione e fonti", async () => {
  const [app, css] = await Promise.all([
    readFile(new URL("../app/FoodPlanner.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
  ]);
  assert.match(app, /VERSION = "1\.16\.25"/);
  assert.match(app, /breakfastMilkAlternatives/);
  assert.match(app, /recipeFlours/);
  assert.match(app, /sharesFruit/);
  assert.match(app, /slot !== 2 && slot !== 4/);
  assert.match(app, /sameCuisineFamily/);
  assert.match(app, /const uniqueRecipes/);
  assert.match(app, /sameCuisine\.length/);
  assert.match(app, /setCuisineFilter\("Tutte"\)/);
  assert.match(app, /recipeCuisine\(b\) === cuisineChoice/);
  assert.match(app, /calibratePlannedIngredients/);
  assert.match(app, /const cookedGrain/);
  assert.match(app, /roundWithin\(120, 250, 10\)/);
  assert.match(app, /\.\.\.mealPartOptions\.Proteina/);
  assert.match(app, /targetAdditionsFor\(slot, targetForDay\(day\)\)/);
  assert.match(app, /mealCalorieShares/);
  assert.match(app, /max: 100, step: 10/);
  assert.match(app, /refreshSnapshotRef/);
  assert.match(app, /setMealView\(s\.mealView/);
  assert.match(css, /add-part-compact::before/);
  assert.match(app, /const rawRecipes: Recipe\[\]/);
  assert.match(app, /pantryPartByFood/);
  assert.match(app, /isSubstantialRecipe/);
  assert.match(app, /Cambia piatto pronto/);
  assert.match(app, /setCuisineFilter\(recipeCuisine\(r\)\)/);
  assert.match(app, /startAddingMealPart/);
  assert.match(app, /className="add-part-compact"/);
  assert.match(app, /title="Aggiungi elemento"/);
  assert.match(app, /partPicker\.adding/);
  assert.match(app, /filter\(\(\{ part \}\) => part\.grams > 0\)/);
  assert.match(css, /\.week-part-add/);
  assert.match(app, /food: "Crescenza"/);
  assert.match(app, /food: "Primo sale"/);
  assert.match(app, /food: "Scamorza"/);
  assert.match(app, /food: "Provolone Dolce Auricchio"/);
  assert.match(app, /horse-steak-potatoes-zucchini/);
  assert.match(app, /matrix-d41-sole-potatoes-fennel/);
  assert.match(app, /matrix-d42-chicken-brown-rice-peppers/);
  assert.match(app, /matrix-d43-grass-pea-soup/);
  assert.match(app, /matrix-d44-artichoke-frittata/);
  assert.match(app, /matrix-d45-tempeh-sweet-potato/);
  assert.match(app, /matrix-d46-turbot-quinoa-zucchini/);
  assert.match(app, /matrix-d47-ricotta-pumpkin-radicchio/);
  assert.match(app, /matrix-d48-cuttlefish-chard-basmati/);
  assert.match(app, /asian-oyakodon-authentic/);
  assert.match(app, /asian-bibimbap-authentic/);
  assert.match(app, /asian-negima-nabe-authentic/);
  assert.match(app, /asian-japchae-authentic/);
  assert.match(app, /asian-phat-thai-authentic/);
  assert.match(app, /Fonte verificata:/);
  assert.match(app, /sourceUrl/);
  assert.match(app, /Piatti completi consigliati/);
  assert.match(app, /chooseCompleteMeal/);
  assert.match(app, /complete-meal-info/);
  assert.match(app, /Vedi ingredienti e preparazione/);
  assert.match(app, /Scegli questo piatto/);
  assert.match(app, /Cambia ricetta/);
  assert.match(app, /Cambia un elemento/);
  assert.match(app, /recipe-mode-actions/);
  assert.match(app, /recipe-card-choose/);
  assert.match(app, /recipe-preview-choose/);
  assert.match(app, /Note utili/);
  assert.match(app, /italian-minestrone-complete/);
  assert.match(app, /Peperoni crudi/);
  assert.match(app, /Peperoni cotti senza olio/);
  assert.match(app, /Mozzarella vaccina/);
  assert.match(app, /Mozzarella light/);
  assert.match(app, /Yogurt greco 0%/);
  assert.match(app, /food: "Quinoa cotta"/);
  assert.match(app, /recipe\.parts \|\| recipe\.ingredients\.map\(additionAsPart\)/);
  assert.match(app, /!recipe\.parts && !partSelections\[key\]/);
  assert.match(app, /cleanKicker/);
  assert.match(app, /matrice\\s\+\[cspd\]/);
  assert.match(app, /Ricetta e preparazione/);
  assert.match(app, /Dividi in componenti/);
  assert.match(app, /Piatto unico/);
  assert.match(app, /workLunchesFrom/);
  assert.match(app, /mealView/);
  assert.match(app, /normalizeMealPart/);
  assert.match(app, /window\.location\.replace/);
  assert.match(app, /searchParams\.set\("_release"/);
  assert.match(app, /swapTarget \|\|/);
  assert.match(app, /history\.replaceState/);
  assert.match(app, /Seleziona tutto/);
  assert.match(app, /Deseleziona tutto/);
  assert.match(app, /week-kcal-summary/);
  assert.match(app, /Rotazione confermata/);
  assert.match(app, /simpleBreakfasts\.forEach\(\(recipe\) => \(recipe\.kind = "combination"\)\)/);
  const realRecipeIndex = app.slice(app.indexOf("const rawRecipes"), app.indexOf("const pantryPartByFood"));
  assert.match(realRecipeIndex, /catalogMains/);
  assert.doesNotMatch(realRecipeIndex, /generatedRecipes|snackRecipes/);
  assert.match(app, /const RecipeVisual/);
  assert.match(app, /recipe-visual-parts/);
  assert.match(app, /verifiedWorldRecipeExpansion/);
  assert.match(app, /Torna indietro senza cambiare piatto/);
  assert.match(css, /\.swap-back/);
  assert.match(app, /catalog-verified-bulgogi-rice/);
  assert.match(app, /catalog-verified-keihan/);
  assert.match(app, /catalog-verified-lentil-pumpkin-bulgur/);
  assert.match(app, /VisitKorea · Bulgogi with rice/);
  assert.match(app, /Harvard T\.H\. Chan · Healthy Eating Plate/);
  assert.match(app, /version\.json/);
  assert.match(app, /part-grissini-v112/);
  assert.match(app, /matrix-c21-porridge-banana-peanut/);
  assert.match(app, /matrix-s11-banana-peanut/);
  assert.match(app, /matrix-s27-apricot-almond/);
  assert.match(app, /matrix-s34-rye-ricotta-radish/);
  assert.match(app, /matrix-s02-yogurt-blueberries/);
  assert.match(app, /matrix-s09-unsweetened-yogurt-smoothie/);
  assert.match(app, /matrix-s12-mandarins-walnuts/);
  assert.match(app, /matrix-s13-skyr-pomegranate/);
  assert.match(app, /matrix-s19-peach-cashews/);
  assert.match(app, /matrix-p41-whole-pasta-peas-ricotta/);
  assert.match(app, /matrix-p42-basmati-cod-spinach/);
  assert.match(app, /matrix-p44-quinoa-cannellini-beet/);
  assert.match(app, /matrix-p48-legume-pasta-salmon/);
  assert.match(app, /matrix-p52-bulgur-tofu-chickpeas/);
  assert.match(app, /Hummus di barbabietola/);
  assert.match(app, /weeklyPlannedFiber\[index\]\} g fibre/);
  assert.match(app, /WEEKLY_MAIN_ROTATION/);
  assert.match(app, /occasionalFoodRows/);
  assert.match(app, /foodSearchDatabase/);
  assert.match(app, /Sgarri ed extra/);
  assert.match(app, /Pizza quattro formaggi/);
  assert.match(app, /stima da ricetta/);
  assert.match(app, /proteinFamilyForItems/);
  assert.match(app, /Legumi e vegetali/);
  assert.match(app, /setCuisineChoice\(s\.cuisineChoice/);
  assert.match(app, /tab === "builder"/);
  await access(new URL("../dist/food/recipe-d41-sole-potatoes-fennel-v11519.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d42-chicken-brown-rice-v11519.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d43-grass-pea-soup-v11519.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d44-artichoke-frittata-v11519.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d45-tempeh-sweet-potato-v11520.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d46-turbot-quinoa-v11520.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d47-ricotta-pumpkin-v11520.png", import.meta.url));
  await access(new URL("../dist/food/recipe-d48-cuttlefish-chard-v11520.png", import.meta.url));
  await access(new URL("../dist/food/recipe-asian-oyakodon-v11520.png", import.meta.url));
  await access(new URL("../dist/food/recipe-asian-bibimbap-v11520.png", import.meta.url));
  await access(new URL("../dist/food/part-tempeh-v11520.png", import.meta.url));
  await access(new URL("../dist/food/part-turbot-v11520.png", import.meta.url));
  await access(new URL("../dist/food/part-cuttlefish-v11520.png", import.meta.url));
  await access(new URL("../dist/food/part-sprouts-v11520.png", import.meta.url));
  await access(new URL("../dist/food/part-peppers-raw-v11522.png", import.meta.url));
  await access(new URL("../dist/food/part-peppers-cooked-v11522.png", import.meta.url));
  await access(new URL("../dist/food/part-mozzarella-v11522.png", import.meta.url));
  await access(new URL("../dist/food/part-mozzarella-light-v11522.png", import.meta.url));
  await access(new URL("../dist/food/part-greek-yogurt-zero-v11522.png", import.meta.url));
  await access(new URL("../dist/food/recipe-minestrone-v11522.png", import.meta.url));
  await access(new URL("../dist/food/part-sole-baked-v11519.png", import.meta.url));
  await access(new URL("../dist/food/part-brown-rice-v11519.png", import.meta.url));
  await access(new URL("../dist/food/part-grass-peas-v11519.png", import.meta.url));
  await access(new URL("../dist/food/part-artichokes-v11519.png", import.meta.url));
  await access(new URL("../dist/food/part-onions-v11519.png", import.meta.url));
  await access(new URL("../dist/food/part-crescenza-v11518.png", import.meta.url));
  await access(new URL("../dist/food/part-primo-sale-v11518.png", import.meta.url));
  await access(new URL("../dist/food/part-scamorza-v11518.png", import.meta.url));
  await access(new URL("../dist/food/part-provolone-auricchio-v11518.png", import.meta.url));
  await access(new URL("../dist/food/recipe-horse-steak-potatoes-zucchini-v11518.png", import.meta.url));
  await access(new URL("../dist/food/part-pineapple-v11513.png", import.meta.url));
  await access(new URL("../dist/food/part-beet-hummus-v11513.png", import.meta.url));
  await access(new URL("../dist/food/recipe-p41-pasta-peas-ricotta-v11513.png", import.meta.url));
  await access(new URL("../dist/food/part-carrots-raw-v11512.png", import.meta.url));
  await access(new URL("../dist/food/part-carrots-cooked-v11512.png", import.meta.url));
  await access(new URL("../dist/food/part-radishes-v11512.png", import.meta.url));
  await access(new URL("../dist/food/recipe-c21-porridge-banana-peanut-v113.png", import.meta.url));
  await access(new URL("../dist/food/part-peanuts-v113.png", import.meta.url));
  await access(new URL("../dist/food/part-blueberries-v1160.png", import.meta.url));
  await access(new URL("../dist/food/part-mandarins-v1160.png", import.meta.url));
  await access(new URL("../dist/food/part-pomegranate-v1160.png", import.meta.url));
  await access(new URL("../dist/food/part-cashews-v1160.png", import.meta.url));
  await access(new URL("../dist/food/recipe-s02-yogurt-blueberries-v1160.png", import.meta.url));
  await access(new URL("../dist/food/recipe-s09-yogurt-fruit-smoothie-v1160.png", import.meta.url));
  await access(new URL("../dist/food/recipe-s12-mandarins-walnuts-v1160.png", import.meta.url));
  await access(new URL("../dist/food/recipe-s13-skyr-pomegranate-v1160.png", import.meta.url));
  await access(new URL("../dist/food/recipe-s19-peach-cashews-v1160.png", import.meta.url));
  assert.match(app, /matrix-c31-spelt-ricotta-apple/);
  assert.match(app, /matrix-c34-buckwheat-pancakes-pear/);
  assert.match(app, /matrix-c35-skyr-melon-chia/);
  assert.match(app, /matrix-c36-cereal-hazelnut-strawberry/);
  assert.match(app, /mainCompatibilityMatrix/);
  await access(new URL("../dist/food/recipe-c31-spelt-ricotta-apple-v11511.png", import.meta.url));
  await access(new URL("../dist/food/part-hazelnut-paste-v11511.png", import.meta.url));
  assert.match(app, /length:\s*284/);
  assert.match(app, /300\+ RICETTE GUIDATE/);
  assert.match(app, /CREA/);
  assert.match(app, /USDA/);
  assert.match(css, /overflow-x:\s*hidden/);
  assert.match(css, /max-width:\s*520px/);
  await access(new URL("../dist/food/recipe-asian-negima-v1163.png", import.meta.url));
  await access(new URL("../dist/food/recipe-asian-japchae-v1163.png", import.meta.url));
  await access(new URL("../dist/food/recipe-asian-phat-thai-v1163.png", import.meta.url));
  await access(new URL("../dist/food/part-lime-v1163.png", import.meta.url));
  await access(new URL("../dist/food/part-leek-v1163.png", import.meta.url));
  await access(new URL("../dist/food/part-garlic-chives-v1163.png", import.meta.url));
  const referencedPhotos = [...app.matchAll(/photo\("([^"]+)"\)/g)].map((match) => match[1]);
  await Promise.all(
    [...new Set(referencedPhotos)].map((name) =>
      access(new URL(`../dist/food/${name}.png`, import.meta.url)),
    ),
  );
});


test("v1.16.17 keeps swap navigation visible and exposes occasional choices", async () => {
  const app = await readFile(new URL("../app/FoodPlanner.tsx", import.meta.url), "utf8");
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(app, /swap-back-bar/);
  assert.match(app, /aria-label="Torna indietro senza cambiare piatto"/);
  assert.match(app, /<summary>Sgarri<\/summary>/);
  assert.match(app, /r\.id\.startsWith\("occasional-"\)/);
  assert.match(css, /\.swap-back-bar\s*\{[\s\S]*position:\s*fixed/);
  await access(new URL("../dist/food/part-pasta-whole-v11618.png", import.meta.url));
  await access(new URL("../dist/food/part-pasta-semolina-v11618.png", import.meta.url));
  assert.match(app, /photo\("part-pasta-whole-v11618"\)/);
  assert.match(app, /photo\("part-pasta-semolina-v11618"\)/);
  assert.match(app, /occasional-carbonara/);
  assert.match(app, /occasional-gelato/);
  assert.match(app, /occasional-tiramisu/);
  assert.match(app, /occasional-fries/);
  assert.match(app, /foods\[item\.food\] \?\? occasionalFoods\[item\.food\]/);
  assert.doesNotMatch(app, /},,/);
  assert.match(app, /const GELATO_FLAVORS/);
  assert.match(app, /chooseConfiguredGelato/);
  assert.match(app, /gelatoScoops === count/);
  assert.match(app, /Gusto pallina/);
  assert.match(css, /\.gelato-builder/);
  assert.match(app, /gelatoComposerOpen && \[1, 3\]/);
  assert.match(app, /Chiudi composizione gelato/);
  assert.match(app, /↻ Cambia piatto/);
  assert.match(app, /swapFoodOptions/);
  assert.match(app, /chooseSingleFoodFromLibrary/);
  assert.match(app, /Ricomponi piatto/);
  assert.match(app, /occasional-amatriciana/);
  assert.match(app, /cheat-amatriciana-v11625/);
  assert.match(css, /\.swap-food-grid/);
});
