export type FoodRole =
  | "Carboidrato"
  | "Proteina"
  | "Contorno"
  | "Condimento"
  | "Colazione";

export type StandardFood = {
  id: string;
  label: string;
  role: FoodRole;
  portion: number;
  unit: "g" | "ml";
  state: "secco" | "crudo" | "cotto" | "pronto";
  kcal100: number;
  protein100: number;
  carbs100: number;
  fat100: number;
  cuisine: "Italiano" | "Orientale" | "Entrambi";
  note: string;
};

export const STANDARD_SOURCES = [
  "CREA — Linee guida per una sana alimentazione 2018, tabella porzioni adulti",
  "SINU — LARN V revisione, Standard quantitativi delle porzioni 2024",
  "Ministero della Salute e ISS — modello mediterraneo, varietà e frequenze",
  "Singapore Health Promotion Board — My Healthy Plate, ¼ cereali + ¼ proteine + ½ vegetali",
  "Ministero della Salute giapponese — alimento base + piatto proteico + contorno",
];

export const standardFoods: StandardFood[] = [
  {
    id: "pasta-semola",
    label: "Pasta di semola",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 353,
    protein100: 13,
    carbs100: 71.5,
    fat100: 1.5,
    cuisine: "Italiano",
    note: "Porzione standard italiana; 40 g nelle minestre.",
  },
  {
    id: "pasta-integrale",
    label: "Pasta integrale",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 348,
    protein100: 14,
    carbs100: 66,
    fat100: 2.5,
    cuisine: "Italiano",
    note: "Più fibra; non automaticamente migliore se mal tollerata.",
  },
  {
    id: "pasta-lenticchie",
    label: "Pasta di lenticchie",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 334,
    protein100: 25,
    carbs100: 50,
    fat100: 2,
    cuisine: "Italiano",
    note: "Apporta anche proteine e fibra; verificare etichetta della marca.",
  },
  {
    id: "pasta-ceci",
    label: "Pasta di ceci",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 350,
    protein100: 21,
    carbs100: 55,
    fat100: 5,
    cuisine: "Italiano",
    note: "Può essere poco adatta nel giorno con gonfiore.",
  },
  {
    id: "pasta-fresca",
    label: "Pasta fresca all'uovo",
    role: "Carboidrato",
    portion: 100,
    unit: "g",
    state: "crudo",
    kcal100: 288,
    protein100: 11,
    carbs100: 55,
    fat100: 4,
    cuisine: "Italiano",
    note: "Porzione standard diversa dalla pasta secca.",
  },
  {
    id: "gnocchi",
    label: "Gnocchi di patate",
    role: "Carboidrato",
    portion: 150,
    unit: "g",
    state: "pronto",
    kcal100: 155,
    protein100: 4,
    carbs100: 33,
    fat100: 0.7,
    cuisine: "Italiano",
    note: "Peso pronto da cuocere; condimento conteggiato a parte.",
  },
  {
    id: "riso-basmati",
    label: "Riso basmati",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 356,
    protein100: 8,
    carbs100: 78,
    fat100: 0.8,
    cuisine: "Entrambi",
    note: "Peso secco prima della cottura.",
  },
  {
    id: "riso-venere",
    label: "Riso Venere",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 355,
    protein100: 8.5,
    carbs100: 73,
    fat100: 2.8,
    cuisine: "Entrambi",
    note: "Tempi di cottura più lunghi; buona tenuta per schiscetta.",
  },
  {
    id: "riso-integrale",
    label: "Riso integrale",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 350,
    protein100: 7.5,
    carbs100: 72,
    fat100: 2.7,
    cuisine: "Entrambi",
    note: "Più fibra; valutare tolleranza individuale.",
  },
  {
    id: "noodles-integrali",
    label: "Noodles integrali",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 350,
    protein100: 12,
    carbs100: 70,
    fat100: 2.5,
    cuisine: "Orientale",
    note: "Sodio e valori cambiano per marca: controllare etichetta.",
  },
  {
    id: "soba",
    label: "Soba di grano saraceno",
    role: "Carboidrato",
    portion: 80,
    unit: "g",
    state: "secco",
    kcal100: 340,
    protein100: 14,
    carbs100: 68,
    fat100: 2,
    cuisine: "Orientale",
    note: "Verificare percentuale reale di grano saraceno.",
  },
  {
    id: "pane",
    label: "Pane",
    role: "Carboidrato",
    portion: 50,
    unit: "g",
    state: "pronto",
    kcal100: 265,
    protein100: 9,
    carbs100: 49,
    fat100: 3.2,
    cuisine: "Entrambi",
    note: "Una porzione; un panino completo può usarne due.",
  },
  {
    id: "patate",
    label: "Patate lesse",
    role: "Carboidrato",
    portion: 200,
    unit: "g",
    state: "cotto",
    kcal100: 87,
    protein100: 1.9,
    carbs100: 20.1,
    fat100: 0.1,
    cuisine: "Entrambi",
    note: "Sono fonte amidacea, non sostituto equivalente dell'insalata.",
  },
  {
    id: "pollo",
    label: "Petto di pollo",
    role: "Proteina",
    portion: 100,
    unit: "g",
    state: "cotto",
    kcal100: 165,
    protein100: 31,
    carbs100: 0,
    fat100: 3.6,
    cuisine: "Entrambi",
    note: "Piastra, forno, vapore o salto rapido.",
  },
  {
    id: "tacchino",
    label: "Fesa di tacchino",
    role: "Proteina",
    portion: 100,
    unit: "g",
    state: "cotto",
    kcal100: 135,
    protein100: 29,
    carbs100: 0,
    fat100: 1.8,
    cuisine: "Entrambi",
    note: "Distinguere carne fresca da affettato più salato.",
  },
  {
    id: "manzo",
    label: "Bistecca magra",
    role: "Proteina",
    portion: 100,
    unit: "g",
    state: "cotto",
    kcal100: 217,
    protein100: 26,
    carbs100: 0,
    fat100: 12,
    cuisine: "Entrambi",
    note: "Alternare con pesce, uova, legumi e carni bianche.",
  },
  {
    id: "uova",
    label: "Uova",
    role: "Proteina",
    portion: 100,
    unit: "g",
    state: "pronto",
    kcal100: 143,
    protein100: 12.6,
    carbs100: 0.7,
    fat100: 9.5,
    cuisine: "Entrambi",
    note: "Circa due uova medie; sode, in padella o frittata.",
  },
  {
    id: "salmone",
    label: "Salmone",
    role: "Proteina",
    portion: 150,
    unit: "g",
    state: "cotto",
    kcal100: 208,
    protein100: 20.4,
    carbs100: 0,
    fat100: 13.4,
    cuisine: "Entrambi",
    note: "Più ricco di grassi rispetto ai pesci magri.",
  },
  {
    id: "tofu",
    label: "Tofu",
    role: "Proteina",
    portion: 150,
    unit: "g",
    state: "pronto",
    kcal100: 120,
    protein100: 13,
    carbs100: 2,
    fat100: 7,
    cuisine: "Orientale",
    note: "Controllare sodio e marinature.",
  },
  {
    id: "legumi",
    label: "Legumi cotti",
    role: "Proteina",
    portion: 150,
    unit: "g",
    state: "cotto",
    kcal100: 120,
    protein100: 8,
    carbs100: 20,
    fat100: 1,
    cuisine: "Entrambi",
    note: "Proteine vegetali e carboidrati; cautela solo se il check-in segnala gonfiore.",
  },
  {
    id: "verdure-cotte",
    label: "Verdure cotte",
    role: "Contorno",
    portion: 200,
    unit: "g",
    state: "cotto",
    kcal100: 35,
    protein100: 2,
    carbs100: 6,
    fat100: 0.4,
    cuisine: "Entrambi",
    note: "Zucchine, fagiolini, carote, funghi, broccoli o spinaci.",
  },
  {
    id: "insalata",
    label: "Insalata a foglia",
    role: "Contorno",
    portion: 80,
    unit: "g",
    state: "crudo",
    kcal100: 20,
    protein100: 1.5,
    carbs100: 3,
    fat100: 0.2,
    cuisine: "Entrambi",
    note: "Peso diverso dalle verdure cotte; condimento a parte.",
  },
  {
    id: "olio",
    label: "Olio extravergine",
    role: "Condimento",
    portion: 10,
    unit: "g",
    state: "pronto",
    kcal100: 884,
    protein100: 0,
    carbs100: 0,
    fat100: 100,
    cuisine: "Italiano",
    note: "Un cucchiaio raso circa; quantità discrete, non scaling libero.",
  },
  {
    id: "latte",
    label: "Latte parzialmente scremato",
    role: "Colazione",
    portion: 200,
    unit: "ml",
    state: "pronto",
    kcal100: 46,
    protein100: 3.3,
    carbs100: 4.9,
    fat100: 1.6,
    cuisine: "Entrambi",
    note: "Elemento della colazione, non bevanda obbligatoria della giornata.",
  },
  {
    id: "yogurt",
    label: "Yogurt",
    role: "Colazione",
    portion: 125,
    unit: "g",
    state: "pronto",
    kcal100: 73,
    protein100: 9.9,
    carbs100: 3.9,
    fat100: 2,
    cuisine: "Entrambi",
    note: "Un vasetto standard; possibile seconda porzione da 250 g.",
  },
];

export const portionOptions = (role: FoodRole, cuisine?: string) =>
  standardFoods.filter(
    (x) =>
      x.role === role &&
      (!cuisine || x.cuisine === "Entrambi" || x.cuisine === cuisine),
  );

export const discretePortion = (food: StandardFood, multiplier = 1) => ({
  ...food,
  grams: food.portion * Math.max(0.5, Math.round(multiplier * 2) / 2),
});
